GET http://127.0.0.1:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAxMjYwNTU5LCJpYXQiOjE3MDEyNTQ1NTksImp0aSI6IjU0YTcxMGNmZDI5MTQzMmM4M2Y3NzZjZjM2MGMwZDlkIiwidXNlcl9pZCI6M30.OvNOz6khzYlr_4H3Cj4qZ-yoCmTqOF9CLuKDlB6j-7c
