# Generated by Django 4.2.7 on 2023-12-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course", "Курс"),
                            ("article", "Статья"),
                            ("podcast", "Подкаст"),
                            ("other", "Другое"),
                        ],
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("learning_time", models.IntegerField(verbose_name="Время изучения")),
                ("url", models.URLField(verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Библиотека ресурсов",
                "verbose_name_plural": "Библиотеки ресурсов",
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Группа навыка",
                "verbose_name_plural": "Группы навыков",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название должности"),
                ),
                ("code", models.IntegerField(verbose_name="Код профессии")),
                ("level_code", models.IntegerField(verbose_name="Код уровня")),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("none", "Не знаю"),
                            ("jun", "Junior"),
                            ("mid", "Middle"),
                            ("mid+", "Middle+"),
                            ("sen", "Senior"),
                            ("sen+", "Senior+"),
                        ],
                        max_length=4,
                        verbose_name="Название уровня",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сфера работы",
                "verbose_name_plural": "Сферы работы",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название навыка"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "type",
                    models.CharField(
                        choices=[("soft", "Софт скилл"), ("hard", "Хард скилл")],
                        max_length=4,
                        verbose_name="Тип навыка",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("start", "Базовый"),
                            ("middle", "Средний"),
                            ("senior", "Продвинутый"),
                        ],
                        max_length=6,
                        verbose_name="Уровень навыка",
                    ),
                ),
                ("code", models.IntegerField()),
                (
                    "date_from",
                    models.DateField(verbose_name="Дата начала действия навыка"),
                ),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата окончания действия навыка",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skill_group",
                        to="skills.skillgroup",
                        verbose_name="Группа навыка",
                    ),
                ),
                (
                    "resource_library",
                    models.ManyToManyField(
                        related_name="resource_library",
                        to="skills.resourcelibrary",
                        verbose_name="Библиотека ресурсов",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skill_specialization",
                        to="skills.specialization",
                        verbose_name="Сфера работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ("id",),
            },
        ),
    ]
