# Generated by Django 4.2.7 on 2023-11-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("none", "Не знаю"),
                            ("jun", "Junior"),
                            ("mid", "Middle"),
                            ("mid+", "Middle+"),
                            ("sen", "Senior"),
                            ("sen+", "Senior+"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уровень должности",
                "verbose_name_plural": "Уровни должности",
            },
        ),
        migrations.CreateModel(
            name="ResourceLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course", "Курс"),
                            ("article", "Статья"),
                            ("podcast", "Подкаст"),
                            ("other", "Другое"),
                        ],
                        max_length=8,
                    ),
                ),
                ("description", models.TextField()),
                ("learning_time", models.IntegerField()),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Библиотека ресурсов",
                "verbose_name_plural": "Библиотеки ресурсов",
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Группа навыка",
                "verbose_name_plural": "Группы навыков",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("code", models.IntegerField()),
            ],
            options={
                "verbose_name": "Сфера работы",
                "verbose_name_plural": "Сферы работы",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название навыка"),
                ),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("soft", "Софт скилл"), ("hard", "Хард скилл")],
                        max_length=4,
                        verbose_name="Тип навыка",
                    ),
                ),
                ("code", models.IntegerField()),
                (
                    "date_from",
                    models.DateField(verbose_name="Дата начала действия навыка"),
                ),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата окончания действия навыка",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skill_group",
                        to="skills.skillgroup",
                        verbose_name="Группа навыка",
                    ),
                ),
                (
                    "post_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_level",
                        to="skills.postlevel",
                        verbose_name="Уровень должности",
                    ),
                ),
                (
                    "resource_library",
                    models.ManyToManyField(
                        related_name="resource_library",
                        to="skills.resourcelibrary",
                        verbose_name="Библиотека ресурсов",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skill_specialization",
                        to="skills.specialization",
                        verbose_name="Сфера работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.AddField(
            model_name="postlevel",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_specialization",
                to="skills.specialization",
                verbose_name="Сфера работы",
            ),
        ),
    ]
