# Generated by Django 4.2.7 on 2023-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("start", "Базовый"),
                    ("middle", "Средний"),
                    ("senior", "Продвинутый"),
                ],
                default="start",
                max_length=6,
                verbose_name="Уровень навыка",
            ),
            preserve_default=False,
        ),
    ]
