# Generated by Django 4.2.7 on 2023-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_skill_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcelibrary",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="resourcelibrary",
            name="learning_time",
            field=models.IntegerField(verbose_name="Время изучения"),
        ),
        migrations.AlterField(
            model_name="resourcelibrary",
            name="type",
            field=models.CharField(
                choices=[
                    ("course", "Курс"),
                    ("article", "Статья"),
                    ("podcast", "Подкаст"),
                    ("other", "Другое"),
                ],
                max_length=8,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="resourcelibrary",
            name="url",
            field=models.URLField(verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="skillgroup",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="code",
            field=models.IntegerField(verbose_name="Код профессии"),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="level_code",
            field=models.IntegerField(verbose_name="Код уровня"),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="level_name",
            field=models.CharField(
                choices=[
                    ("none", "Не знаю"),
                    ("jun", "Junior"),
                    ("mid", "Middle"),
                    ("mid+", "Middle+"),
                    ("sen", "Senior"),
                    ("sen+", "Senior+"),
                ],
                max_length=4,
                verbose_name="Название уровня",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название должности"),
        ),
    ]
