# Generated by Django 4.2.7 on 2023-11-27 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSkills",
            new_name="UserSkill",
        ),
    ]
