# Generated by Django 4.2.7 on 2023-12-01 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_userskills_userskill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="trecker_id",
        ),
    ]
